<a href="https://colab.research.google.com/github/JaehwanKim00/Bigdata_python/blob/main/Part01/ch02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이썬으로 데이터 다루기


## NumPy

In [ ]:
import numpy as np
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
ar3 = np.random.randn(3)
ar4 = np.random.randn(2,3)
print(ar3)
print(ar4)

[-0.79601899 -0.191567   -0.7148941 ]
[[-2.34568823 -1.90696752  0.67711482]
 [ 0.79373159 -0.1086978   0.95297495]]


In [ ]:
ar5 = np.zeros(5)
ar6 = np.ones((2,3))
print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
ar7 = np.arange(20,200,10)
ar8 = ar7.reshape(3,6)
print(ar7)
print(ar8)

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


In [ ]:
ar1 = np.arange(1,21,1)
print(ar1)
print(ar1[1])

ar2 = ar1.reshape(2,10)
print(ar2)
ar2[1][1] = 100
print(ar2[1][0],ar2[1][1],ar2[1][2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
11 100 13


In [ ]:
ar1 = np.arange(1,11,1)
ar2 = ar1+3
ar3 = ar1*2
print(ar1)
print(ar2,'\n',ar3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0)) # 각 열의 원소 중 가장 큰 값
print(ar1.max(axis=1)) # 각 행의 원소 중 가장 큰 값

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]


In [ ]:
# 조건식 사용한 연산
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1>0)
m_count = (ar1<0).sum() # 0보다 작은 원소 count
print(m_count)

ar2 = np.where(ar1<0,0,ar1) # 0보다 작으면 0 대입
print(ar2)

[[ True  True  True]
 [False False  True]
 [ True  True  True]]
2
[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


In [ ]:
# 배열의 정렬
ar1 = np.array([[5,7,9],[-3,-6,19],[6,4,11]])
print(ar1)
ar1.sort(0) # 열단위로 원소 정렬
print(ar1)
ar1.sort(1) # 행단위로 원소 정렬(열단위로 정렬 반영 후 행단위 정렬)
print(ar1)

[[ 5  7  9]
 [-3 -6 19]
 [ 6  4 11]]
[[-3 -6  9]
 [ 5  4 11]
 [ 6  7 19]]
[[-6 -3  9]
 [ 4  5 11]
 [ 6  7 19]]


In [ ]:
ar1 = np.array([[5,7,9],[-3,-6,19],[6,4,11]])
print(ar1)
ar1.sort(1) # 행단위로 원소 정렬
print(ar1)

[[ 5  7  9]
 [-3 -6 19]
 [ 6  4 11]]
[[ 5  7  9]
 [-6 -3 19]
 [ 4  6 11]]


## Pandas

In [1]:
import pandas as pd

In [ ]:
sr1 = pd.Series([10,20,30,40,60])
print(sr1)

0    10
1    20
2    30
3    40
4    60
dtype: int64


In [ ]:
sr1 = pd.Series([10,20,30,40,60])
print(sr1.values)
print(sr1.index)
print(sr1[2])

[10 20 30 40 60]
RangeIndex(start=0, stop=5, step=1)
30


In [ ]:
sr1 = pd.Series([10,30,40,20,60],index = ['a','b','c','d','e']) # 인덱스 설정
print(sr1[1])
print(sr1['b'])

30
30


In [ ]:
sr1 = pd.Series([10,20,30,40,60],index = ['a','b','c','d','e'])
print(sr1[[1,2]])
print(sr1[['a','c']])

b    20
c    30
dtype: int64
a    10
c    30
dtype: int64


In [ ]:
# 범위 설정
sr1 = pd.Series([10,20,30,40,60],index = ['a','b','c','d','e'])
print(sr1[1:4]) # 4 부분 포함 안 됨
print(sr1['b':'d']) # d 부분 포함됨

b    20
c    30
d    40
dtype: int64
b    20
c    30
d    40
dtype: int64


In [ ]:
# 오류
# print(sr1[[1:4]])

In [ ]:
import pandas as pd
df1 = pd.DataFrame([[10,20,30],[50,60,70]])
df1

0   1   2
0  10  20  30
1  50  60  70

In [ ]:
dic1 = {'fruit':['사과','포도','바나나','딸기','귤'],
        'prcie':[100,200,300,400,500],
        'qty':[10,25,60,98,54]}
df1 = pd.DataFrame(dic1)
df1

fruit  prcie  qty
0    사과    100   10
1    포도    200   25
2   바나나    300   60
3    딸기    400   98
4     귤    500   54

In [ ]:
df1 = pd.DataFrame(dic1,index = ['a','b','c','d','e'])
print(df1)

  fruit  prcie  qty
a    사과    100   10
b    포도    200   25
c   바나나    300   60
d    딸기    400   98
e     귤    500   54


In [ ]:
df1.rename(columns = {'fruit':'과일','price':'가격','qty':'수량'},inplace=True)
df1.rename(index = {'a':'01','b':'02','c':'03','d':'04','e':'05'},inplace=True)
print(df1)

     과일  prcie  수량
01   사과    100  10
02   포도    200  25
03  바나나    300  60
04   딸기    400  98
05    귤    500  54


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df1 = pd.read_csv('/content/drive/MyDrive/빅분기_실기/data/csv/df_sample.csv')

In [5]:
df1

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
5  S06  71  75   16  16
6  S07  60  80   18  18
7  S08  72  65   14  14
8  S09  65  65   14  14
9  S10  85  78   10  10

In [6]:
df1.head(5)

학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12

In [7]:
df1.shape

(10, 5)

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   학번      10 non-null     object
 1   중간      10 non-null     int64 
 2   기말      10 non-null     int64 
 3   리포트     10 non-null     int64 
 4   퀴즈      10 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 528.0+ bytes


In [11]:
df1.describe(include='all')

학번         중간         기말        리포트         퀴즈
count    10  10.000000  10.000000  10.000000  10.000000
unique   10        NaN        NaN        NaN        NaN
top     S01        NaN        NaN        NaN        NaN
freq      1        NaN        NaN        NaN        NaN
mean    NaN  77.600000  78.500000  15.000000  15.000000
std     NaN  10.616549   9.663793   3.559026   3.559026
min     NaN  60.000000  65.000000  10.000000  10.000000
25%     NaN  71.250000  75.000000  12.500000  12.500000
50%     NaN  79.000000  78.000000  15.000000  15.000000
75%     NaN  84.250000  82.250000  18.000000  18.000000
max     NaN  93.000000  95.000000  20.000000  20.000000

In [12]:
print(df1['중간'].mean())
print(df1[['중간','기말']].mean())

77.6
중간    77.6
기말    78.5
dtype: float64


In [14]:
print(df1['학번'].min())
print(df1[['중간','기말']].max())
print(df1.select_dtypes(include='number').median()) # 숫자형만 적용

S01
중간    93
기말    95
dtype: int64
중간     79.0
기말     78.0
리포트    15.0
퀴즈     15.0
dtype: float64


In [15]:
print('표준편차 : ')
print(df1[['중간','기말']].std())
print('분산 : ')
print(df1[['중간','기말']].var())

표준편차 : 
중간    10.616549
기말     9.663793
dtype: float64
분산 : 
중간    112.711111
기말     93.388889
dtype: float64


In [16]:
df1['퀴즈'].value_counts()

퀴즈
18    3
10    2
14    2
20    1
12    1
16    1
Name: count, dtype: int64

In [17]:
df1[['중간','기말']].corr()

중간        기말
중간  1.000000  0.707196
기말  0.707196  1.000000

In [19]:
# 숫자형만 선택
df1.select_dtypes(include='number').corr()

중간        기말       리포트        퀴즈
중간   1.000000  0.707196 -0.129388 -0.129388
기말   0.707196  1.000000  0.339210  0.339210
리포트 -0.129388  0.339210  1.000000  1.000000
퀴즈  -0.129388  0.339210  1.000000  1.000000

In [20]:
df1.set_index('학번')

중간  기말  리포트  퀴즈
학번                  
S01  90  95   20  20
S02  82  83   18  18
S03  80  78   18  18
S04  78  75   10  10
S05  93  91   12  12
S06  71  75   16  16
S07  60  80   18  18
S08  72  65   14  14
S09  65  65   14  14
S10  85  78   10  10

In [22]:
df1.index = df1['학번']
df1

학번  중간  기말  리포트  퀴즈
학번                       
S01  S01  90  95   20  20
S02  S02  82  83   18  18
S03  S03  80  78   18  18
S04  S04  78  75   10  10
S05  S05  93  91   12  12
S06  S06  71  75   16  16
S07  S07  60  80   18  18
S08  S08  72  65   14  14
S09  S09  65  65   14  14
S10  S10  85  78   10  10

In [29]:
df1.reset_index(inplace=True)

In [30]:
# 원소 선택
df1.set_index('학번',inplace=True)

print(df1.loc['S01','중간'])
print(df1.loc['S02','기말'])

print(df1.iloc[1,0],df1.iloc[1,1],df1.iloc[1,2])

90
83
82 83 18


In [32]:
df1

중간  기말  리포트  퀴즈
학번                  
S01  90  95   20  20
S02  82  83   18  18
S03  80  78   18  18
S04  78  75   10  10
S05  93  91   12  12
S06  71  75   16  16
S07  60  80   18  18
S08  72  65   14  14
S09  65  65   14  14
S10  85  78   10  10

In [33]:
df1.loc['S05'] # 인덱스명

중간     93
기말     91
리포트    12
퀴즈     12
Name: S05, dtype: int64

In [35]:
df1.iloc[3] # 인덱스 번호

중간     78
기말     75
리포트    10
퀴즈     10
Name: S04, dtype: int64

In [36]:
df1['중간']

학번
S01    90
S02    82
S03    80
S04    78
S05    93
S06    71
S07    60
S08    72
S09    65
S10    85
Name: 중간, dtype: int64

In [37]:
df1[['중간','기말']]

중간  기말
학번         
S01  90  95
S02  82  83
S03  80  78
S04  78  75
S05  93  91
S06  71  75
S07  60  80
S08  72  65
S09  65  65
S10  85  78

In [38]:
# 행, 열 삭제
df1 = pd.read_csv('/content/drive/MyDrive/빅분기_실기/data/csv/df_sample.csv')
df2 =df1.drop(0) # 인덱스 0 행 삭제
df3 = df2.drop('퀴즈',axis=1) # 퀴즈 열 삭제
df3

학번  중간  기말  리포트
1  S02  82  83   18
2  S03  80  78   18
3  S04  78  75   10
4  S05  93  91   12
5  S06  71  75   16
6  S07  60  80   18
7  S08  72  65   14
8  S09  65  65   14
9  S10  85  78   10

In [40]:
df1 = pd.read_csv('/content/drive/MyDrive/빅분기_실기/data/csv/df_sample.csv')

df1.set_index('학번',inplace=True)
df2 = df1.sort_index(ascending=False) # 내림차순
df2

중간  기말  리포트  퀴즈
학번                  
S10  85  78   10  10
S09  65  65   14  14
S08  72  65   14  14
S07  60  80   18  18
S06  71  75   16  16
S05  93  91   12  12
S04  78  75   10  10
S03  80  78   18  18
S02  82  83   18  18
S01  90  95   20  20

In [41]:
df1 = pd.read_csv('/content/drive/MyDrive/빅분기_실기/data/csv/df_sample.csv')

df2 = df1.sort_values(by='기말',ascending=True)
df2

학번  중간  기말  리포트  퀴즈
7  S08  72  65   14  14
8  S09  65  65   14  14
3  S04  78  75   10  10
5  S06  71  75   16  16
2  S03  80  78   18  18
9  S10  85  78   10  10
6  S07  60  80   18  18
1  S02  82  83   18  18
4  S05  93  91   12  12
0  S01  90  95   20  20