# 파이썬으로 데이터 다루기


## NumPy

In [3]:
import numpy as np
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
ar3 = np.random.randn(3)
ar4 = np.random.randn(2,3)
print(ar3)
print(ar4)

[-0.79601899 -0.191567   -0.7148941 ]
[[-2.34568823 -1.90696752  0.67711482]
 [ 0.79373159 -0.1086978   0.95297495]]


In [4]:
ar5 = np.zeros(5)
ar6 = np.ones((2,3))
print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
ar7 = np.arange(20,200,10)
ar8 = ar7.reshape(3,6)
print(ar7)
print(ar8)

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


In [7]:
ar1 = np.arange(1,21,1)
print(ar1)
print(ar1[1])

ar2 = ar1.reshape(2,10)
print(ar2)
ar2[1][1] = 100
print(ar2[1][0],ar2[1][1],ar2[1][2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
11 100 13


In [8]:
ar1 = np.arange(1,11,1)
ar2 = ar1+3
ar3 = ar1*2
print(ar1)
print(ar2,'\n',ar3) 

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [9]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0)) # 각 열의 원소 중 가장 큰 값
print(ar1.max(axis=1)) # 각 행의 원소 중 가장 큰 값

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]


In [5]:
# 조건식 사용한 연산
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1>0)
m_count = (ar1<0).sum() # 0보다 작은 원소 count
print(m_count)

ar2 = np.where(ar1<0,0,ar1) # 0보다 작으면 0 대입
print(ar2)

[[ True  True  True]
 [False False  True]
 [ True  True  True]]
2
[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


In [7]:
# 배열의 정렬
ar1 = np.array([[5,7,9],[-3,-6,19],[6,4,11]])
print(ar1)
ar1.sort(0) # 열단위로 원소 정렬
print(ar1)
ar1.sort(1) # 행단위로 원소 정렬(열단위로 정렬 반영 후 행단위 정렬)
print(ar1)

[[ 5  7  9]
 [-3 -6 19]
 [ 6  4 11]]
[[-3 -6  9]
 [ 5  4 11]
 [ 6  7 19]]
[[-6 -3  9]
 [ 4  5 11]
 [ 6  7 19]]


In [8]:
ar1 = np.array([[5,7,9],[-3,-6,19],[6,4,11]])
print(ar1)
ar1.sort(1) # 행단위로 원소 정렬
print(ar1)

[[ 5  7  9]
 [-3 -6 19]
 [ 6  4 11]]
[[ 5  7  9]
 [-6 -3 19]
 [ 4  6 11]]


## Pandas

In [9]:
import pandas as pd

In [10]:
sr1 = pd.Series([10,20,30,40,60])
print(sr1)

0    10
1    20
2    30
3    40
4    60
dtype: int64


In [11]:
sr1 = pd.Series([10,20,30,40,60])
print(sr1.values)
print(sr1.index)
print(sr1[2])

[10 20 30 40 60]
RangeIndex(start=0, stop=5, step=1)
30


In [12]:
sr1 = pd.Series([10,30,40,20,60],index = ['a','b','c','d','e']) # 인덱스 설정
print(sr1[1])
print(sr1['b'])

30
30


In [14]:
sr1 = pd.Series([10,20,30,40,60],index = ['a','b','c','d','e'])
print(sr1[[1,2]])
print(sr1[['a','c']])

b    20
c    30
dtype: int64
a    10
c    30
dtype: int64


In [15]:
# 범위 설정
sr1 = pd.Series([10,20,30,40,60],index = ['a','b','c','d','e'])
print(sr1[1:4]) # 4 부분 포함 안 됨
print(sr1['b':'d']) # d 부분 포함됨

b    20
c    30
d    40
dtype: int64
b    20
c    30
d    40
dtype: int64


In [17]:
# 오류
# print(sr1[[1:4]])

In [19]:
import pandas as pd
df1 = pd.DataFrame([[10,20,30],[50,60,70]])
df1

0   1   2
0  10  20  30
1  50  60  70

In [21]:
dic1 = {'fruit':['사과','포도','바나나','딸기','귤'],
        'prcie':[100,200,300,400,500],
        'qty':[10,25,60,98,54]}
df1 = pd.DataFrame(dic1)
df1

fruit  prcie  qty
0    사과    100   10
1    포도    200   25
2   바나나    300   60
3    딸기    400   98
4     귤    500   54

In [22]:
df1 = pd.DataFrame(dic1,index = ['a','b','c','d','e'])
print(df1)

  fruit  prcie  qty
a    사과    100   10
b    포도    200   25
c   바나나    300   60
d    딸기    400   98
e     귤    500   54


In [23]:
df1.rename(columns = {'fruit':'과일','price':'가격','qty':'수량'},inplace=True)
df1.rename(index = {'a':'01','b':'02','c':'03','d':'04','e':'05'},inplace=True)
print(df1)

     과일  prcie  수량
01   사과    100  10
02   포도    200  25
03  바나나    300  60
04   딸기    400  98
05    귤    500  54
