# 파이썬으로 데이터 다루기


## 넘파이

In [2]:
import numpy as np
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
ar3 = np.random.randn(3)
ar4 = np.random.randn(2,3)
print(ar3)
print(ar4)

[-0.79601899 -0.191567   -0.7148941 ]
[[-2.34568823 -1.90696752  0.67711482]
 [ 0.79373159 -0.1086978   0.95297495]]


In [4]:
ar5 = np.zeros(5)
ar6 = np.ones((2,3))
print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
ar7 = np.arange(20,200,10)
ar8 = ar7.reshape(3,6)
print(ar7)
print(ar8)

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


In [7]:
ar1 = np.arange(1,21,1)
print(ar1)
print(ar1[1])

ar2 = ar1.reshape(2,10)
print(ar2)
ar2[1][1] = 100
print(ar2[1][0],ar2[1][1],ar2[1][2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
11 100 13


In [8]:
ar1 = np.arange(1,11,1)
ar2 = ar1+3
ar3 = ar1*2
print(ar1)
print(ar2,'\n',ar3) 

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


In [9]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())
print(ar1.mean())
print(ar1.max())
print(ar1.min())
print(ar1.max(axis=0)) # 각 열의 원소 중 가장 큰 값
print(ar1.max(axis=1)) # 각 행의 원소 중 가장 큰 값

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]
